# syntax=docker/dockerfile:1
FROM ubuntu:20.04

USER root

# Install packages required
RUN apt-get update && apt-get install -y \ 
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    software-properties-common

# Add repositories
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - 
RUN apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

# Install packages to docker and terraform
RUN apt-get update && apt install -y \
    docker-ce=5:20.10.9~3-0~ubuntu-focal \
    docker-ce-cli=5:20.10.9~3-0~ubuntu-focal \
    containerd.io \
    terraform=1.0.* \
    && rm -rf /var/lib/apt/lists/*

# Add infrastructure as code by terraform files
RUN mkdir orchestator-terraform
COPY terraform /orchestator-terraform

# keep alive
ENTRYPOINT ["tail", "-f", "/dev/null"]