# syntax=docker/dockerfile:1
FROM centos:centos8

USER root

# Install packages required
RUN yum update -y && yum install -y \
    yum-utils git

# Add repositories
RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
RUN yum --showduplicate list terraform

# Install terraform
RUN yum update && yum install -y \
    terraform-1.0.8

# Install aws-cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
# Configure aws-auth
COPY ./terraform/aws/secret secret
# Fix AWS-CLI v2 -> https://github.com/aws/aws-cli/issues/5038
ENV AWS_PAGER=""
RUN sed -i 's/\r$//' ./secret/keys.sh
RUN ./secret/keys.sh

# remove bridge config
RUN rm awscliv2.zip
RUN rm -rf /terraform-aws/secret

# keep alive
ENTRYPOINT ["tail", "-f", "/dev/null"]