version: "3.4"

services:
  master-ubuntu:
    profiles: ["ubuntu"]
    build:
      context: .
      dockerfile: Dockerfile_ubuntu
    image: pedringcoding/orchestrator:ubuntu2004
    container_name: orchestrator-ubuntu
    restart: always
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

  master-centos:
    profiles: ["centos"]
    build:
      context: .
      dockerfile: Dockerfile_centos
    image: pedringcoding/orchestrator:centos8
    container_name: orchestrator-centos
    restart: always
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock